### ISSUE TITLE
Unable to Launch Phreeqci Version 3.8.2 and 3.8.3 (https://phreeqcusers.org/index.php/topic,2604.0.html)

### ISSUE THREAD

**Issue by scharlton2** [usgs-coupled/phreeqci#3]
Copied from https://phreeqcusers.org/index.php/topic,2604.msg9760.html#msg9760

> Hello,
> 
> I have been using Phreeqci version 3.7.3 on both my Windows 10 and Windows 11 systems without any issues. Recently, I discovered the newer versions (3.8.2 and 3.8.3) on GitHub (https://github.com/usgs-coupled/phreeqci/releases) and downloaded them for installation. However, I am now experiencing a problem where I cannot open the software interface; it gets stuck on the welcome screen displaying "USGS science for a changing world".
> 
> When I try to click on the window while it is stuck, it becomes unresponsive, and I have to close it through the Windows Task Manager.
> 
> I have tried the following troubleshooting steps:
> 
> 1. Restarting my system.
> 2. Uninstalling and reinstalling only the 3.8.2 and 3.8.3 versions of Phreeqci.
> 
> Despite these efforts, the issue persists. Has anyone else encountered this problem? Any suggestions for a solution would be greatly appreciated!
> 
> Thank you!

**Comment by scharlton2** [comment]
Copied from https://phreeqcusers.org/index.php/topic,2604.msg9762.html#msg9762

> Hello ZYWTDaEO6,
> 
> I just tested version 3.8.3 in a clean Windows 11 machine (nothing installed except for Phreeqc Interactive 3.8.3-17023) and I didn't have any issues.
> 
> Since you're having problems with both 3.8.2 and 3.8.3 I think that it is probably caused by a missing or corrupt DLL.
> 
> If you're willing, you could install Process Monitor to see if it detects any problems.  If you don't already have it you can download it  from:
> 
> https://learn.microsoft.com/en-us/sysinternals/downloads/procmon#download
> 
> Here's how to test:
> 
> 1. Start Process Monitor
> 
> 2. Add filters (Filter->Filter...)
>     Select 'Process Name' 'is' phreeqci.exe then 'Include'
>     and add it using the 'Add' button
>  
>     Select 'Operation' 'is' Load Image then 'Include'
>     and add it using the 'Add' button
> 
>     Press the OK button
> 
> 3. Run Phreeqci Interactive 3.8.3-17023 as you normally would
> 
> 4. In the 'Result' column look for any non SUCCESS results
> 
> Let us know if you find anything.
>

**Comment by scharlton2** [comment]
Copied from https://phreeqcusers.org/index.php/topic,2604.msg9767.html#msg9767

> Hi Charlton,
> 
> Thank you very much for your help and detailed instructions! I followed your suggested steps with Process Monitor, including filtering for "phreeqci.exe" and "Load Image" operations. Interestingly, all the results under "Result" showed as "SUCCESS," which suggests no DLL loading errors were detected.
> 
> However, I am still encountering the issue where version 3.8.3 cannot open the software interface, it gets stuck on the welcome screen, while version 3.7.3 runs perfectly fine.
> 
> Since the forum didn't allow me to successfully upload images, would it be possible for me to share screenshots via email? It might provide a clearer picture of what's happening.
> 
> Thanks again for your assistance!

**Comment by scharlton2** [comment]
Copied from https://phreeqcusers.org/index.php/topic,2604.msg9770.html#msg9770

> Hello ZYWTDaEO6,
> 
> I recreated this message thread on github at:
> 
> https://github.com/usgs-coupled/phreeqci/issues/3
> 
> You should be able to upload screenshots there.  You may have to create a github login though.
> 
> You might want to try comparing procmon output for both the 3.7.3 and the 3.8.3 versions to see if you notice any differences.
> 
> When you try to run the 3.8.3 version does the splash screen ever disappear or do you have to kill the phreeqci.exe process?
> 
> Scott

**Comment by wangzitao21** [comment]
![Snipaste_2024-10-26_14-56-30](https://github.com/user-attachments/assets/d3499a5e-2d2e-45b5-b502-074975f8c08b)
[
![1729926081555](https://github.com/user-attachments/assets/7f51b115-d044-4651-98f9-3390d9e80fc0)
](url)
![微信截图_20241026150139](https://github.com/user-attachments/assets/6790d19d-08f4-4af5-852a-808719578237)

**Comment by scharlton2** [comment]
It looks like there's an encoding problem with phreeqc.dat.  Could you try to replace

```C:\Program Files (x86)\USGS\Phreeqc Interactive 3.8.3-17029\database\phreeqc.dat```

with the one in this zip file:

[phreeqc.dat.zip](https://github.com/user-attachments/files/17563875/phreeqc.dat.zip)

**Comment by scharlton2** [comment]
Able to reproduce using AppLocale (AppLoc.exe) with the Simplified Chinese Codepage:
C:\Windows\AppPatch\AppLoc.exe "C:\phreeqci\Debug\phreeqci.exe" "/L0804"
when the default database is encoded using utf-8 (phreeqc-utf8.dat)

**Comment by rubylee0328** [comment]
Excuse, I have a similar condition in  phreeqc 3.8.6, I follow these steps above message, but the issue still persist. Has anyone else encountered this problem? Any suggestions for a solution would be greatly appreciated!
THANK YOU！

**Comment by rubylee0328** [comment]
[Doc1.pdf](https://github.com/user-attachments/files/19862667/Doc1.pdf)

**Comment by Lidong-Huang** [comment]
i have the same issue, and follow the instruction to replace the .dat file, it works!!

**Comment by scharlton2** [comment]
Please try using the latest phreeqci:

https://github.com/usgs-coupled/phreeqci/releases/tag/v3.8.7 (The msi file is at the bottom in the assets)

It includes a fix for an error that occurred when loading certain databases on Windows systems with the locale set to Simplified Chinese.

**Comment by jasonzhu1967** [comment]
> It looks like there's an encoding problem with phreeqc.dat. Could you try to replace
> 
> `C:\Program Files (x86)\USGS\Phreeqc Interactive 3.8.3-17029\database\phreeqc.dat`
> 
> with the one in this zip file:
> 
> [phreeqc.dat.zip](https://github.com/user-attachments/files/17563875/phreeqc.dat.zip)

this finding is amazing. It solved the problem. How did you figure out this?
